NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"
FEDERATION_SERVER="https://api.domain.com/federation"
AUTH_SERVER="https://api.domain.com/auth"
TRANSFER_SERVER="https://api.domain.com"
HORIZON_URL="https://horizon.domain.com"
ACCOUNTS=["GDDOL4F4CUF5PL4GBIBVLHAV7VV43CK6NY5LNFIBQZWPXLSCFANN534G" , "GB65VCALGICYRTVAZBFM4ADBQPAPAPK7PJF5MJEARMVK4GVIDP35BCGT"]
VERSION="2.0.0"

[DOCUMENTATION]
ORG_NAME="Knoxhouse"
ORG_URL="https://knoxhouse.gitbook.io"
ORG_DESCRIPTION="Organization of high-tech era enthusiasts."

[[CURRENCIES]]
code="KNOX"
issuer="GDDOL4F4CUF5PL4GBIBVLHAV7VV43CK6NY5LNFIBQZWPXLSCFANN534G"
image="https://github.com/knoxhouse-org/website/blob/main/AVAG03.png?raw=true"
display_decimals=7
name="KNOX"
desc="KNOX is a governance token for Knoxhouse."
conditions="There will only ever be 1,618,033,988 KNOX tokens in existence."
status="live"
is_asset_anchored=false
fixed_number=1618033988
