VERSION="2.4.1"

NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"

ACCOUNTS=[
"GDDOL4F4CUF5PL4GBIBVLHAV7VV43CK6NY5LNFIBQZWPXLSCFANN534G",
"GB65VCALGICYRTVAZBFM4ADBQPAPAPK7PJF5MJEARMVK4GVIDP35BCGT"
]


[DOCUMENTATION]
ORG_NAME="Knoxhouse"
ORG_URL="https://knoxhouse.gitbook.io"
ORG_DESCRIPTION="Community"

[[CURRENCIES]]
code="KNOX"
issuer="GDDOL4F4CUF5PL4GBIBVLHAV7VV43CK6NY5LNFIBQZWPXLSCFANN534G"
name="KNOX"
desc="KNOX is a governance token for Knoxhouse"
conditions="There will only ever be 1,618,033,988 KNOX tokens in existence"
status="live"
is_asset_anchored=false
image="https://github.com/knoxhouse-org/website/blob/main/logo.png?raw=true"
display_decimals=7
